import type { Household } from "./types.ts";
export const fixtureProfiles: Household[] = [
  [
    "unit-a",
    "Room A",
    "person-a",
    "household-a",
    "bangkok-demo-zone",
    "verified",
  ],
  [
    "duplicate-a",
    "Duplicate A",
    "person-a",
    "household-a",
    "bangkok-demo-zone",
    "verified",
  ],
  [
    "room-b",
    "Independent room B",
    "person-b",
    "household-b",
    "bangkok-demo-zone",
    "verified",
  ],
  [
    "outside-area",
    "Outside area",
    "person-c",
    "household-c",
    "other-area",
    "verified",
  ],
  [
    "pending-room",
    "Pending room",
    "person-d",
    "household-d",
    "bangkok-demo-zone",
    "pending",
  ],
].map((v, i) => ({
  id: v[0]!,
  label: v[1]!,
  home: "Synthetic household",
  personId: v[2]!,
  householdId: v[3]!,
  areaId: v[4]!,
  reviewStatus: v[5]!,
  recipientAddress: "",
  completedAt: new Date(Date.UTC(2026, 9, 4, 0, 0, i)).toISOString(),
  reviewAllocation: false,
}));
