// Walkthrough state lives in memory only. Never serialize receiver fields.
export type ClaimStatus = 'submitted' | 'review' | 'more' | 'approved' | 'rejected' | 'paid';
export interface SampleActivity { ref:string; type:'Donation'|'Household grant'|'Operating support'; amount:number; destination:string; step:string }
export interface DemoState {
 receiver:{name:string;residence:string;room:string;verified:boolean;scenario:'before'|'flood';route:'sol'|'baht';changedResidence:boolean};
 event:'prepared'|'watching'|'review'|'active'; reviewerApproved:boolean; approver:'primary'|'backup'|null;
 claim:null|{status:ClaimStatus;reason:string;history:string[];route:'sol'|'baht'};
 activity:SampleActivity[]; donationCount:number; donorReceipt:null|{amount:number;support:number;route:'sol'|'local';ref:string};
}
const round=(v:number)=>Math.round(v*1e9)/1e9;
export function createDemo():DemoState {return {
 receiver:{name:'',residence:'',room:'',verified:false,scenario:'before',route:'sol',changedResidence:false},event:'prepared',reviewerApproved:false,approver:null,claim:null,donationCount:0,donorReceipt:null,
 activity:[]
};}
export function totals(s:DemoState){const contributions=s.activity.filter(a=>a.type==='Donation').reduce((n,a)=>n+Math.round(a.amount*1e9),0)/1e9;const paid=s.activity.filter(a=>a.type==='Household grant').reduce((n,a)=>n+Math.round(a.amount*1e9),0)/1e9;return {received:round(55920+contributions),reserve:round(48240+contributions-paid),distributed:round(7680+paid),allocated:12000,remainingAllocation:round(4320-paid),support:s.activity.filter(a=>a.type==='Operating support').reduce((n,a)=>n+Math.round(a.amount*1e9),0)/1e9};}
export function submitClaim(s:DemoState){if(!s.receiver.verified)throw Error('Complete demo verification first.');if(s.receiver.scenario!=='flood'||s.event!=='active')throw Error('An approved affected-area event is required.');if(s.claim)throw Error('This household already has a request in this walkthrough.');s.claim={status:s.receiver.changedResidence?'review':'submitted',reason:s.receiver.changedResidence?'Residence changed after the fictional event; human review is required.':'Request received for review.',history:['Submitted'],route:s.receiver.route};}
export function decideClaim(s:DemoState,decision:'approve'|'more'|'reject',reason:string){if(!s.claim||!['submitted','review','more'].includes(s.claim.status))throw Error('Only a pending request can be reviewed.');if(!reason.trim())throw Error('Record a review reason.');s.claim.status=decision==='approve'?'approved':decision==='more'?'more':'rejected';s.claim.reason=reason.trim().slice(0,400);s.claim.history.push(decision==='approve'?'Approved':decision==='more'?'More information needed':'Not approved');}
export function completePayout(s:DemoState){if(s.claim?.status==='paid')throw Error('Already completed; one grant per household.');if(s.claim?.status!=='approved')throw Error('An approved request is required.');if(totals(s).remainingAllocation<.8)throw Error('Awaiting more event allocation.');s.claim.status='paid';s.claim.history.push('Demo payout complete');s.activity.unshift({ref:'SAMPLE-G003',type:'Household grant',amount:.8,destination:s.claim.route==='sol'?'Sample household wallet':'Future baht provider (simulated)',step:'Walkthrough outcome'});}
export function donateSample(s:DemoState,amount:number,support:number,route:'sol'|'local'='sol'){if(!Number.isFinite(amount)||amount<=0||amount>10||!Number.isSafeInteger(Math.round(amount*1e9))||!Number.isFinite(support)||support<0||!Number.isSafeInteger(Math.round(support*1e9))||round(support)!==support)throw Error('Enter a relief amount from 0.001 to 10 SOL and a non-negative support amount with up to 9 decimal places within the demo’s numeric precision.');if(amount<.001)throw Error('Minimum example amount is 0.001 SOL.');s.donationCount++;const ref='SAMPLE-D'+String(s.donationCount+1).padStart(3,'0');s.activity.unshift({ref,type:'Donation',amount:round(amount),destination:'Relief reserve',step:'Your demo contribution'});if(support>0)s.activity.unshift({ref:ref+'-SUPPORT',type:'Operating support',amount:round(support),destination:'Separate operating wallet',step:'Your optional support'});s.donorReceipt={amount:round(amount),support:round(support),route,ref};}
