export interface EventReviewOptions {
 status:'prepared'|'watching'|'review'|'active';recommended:boolean;approver:'primary'|'backup'|null;
 area:string;locked?:boolean;blocked?:string;technical?:boolean;
}
const escape=(v:string)=>v.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export function eventReviewPanel(o:EventReviewOptions){
 const stage=o.status==='active'?4:o.recommended?3:o.status==='review'?2:o.status==='watching'?1:0;
 const labels=['Not started','Watching','Evidence review','Ready for approval','Response approved'];
 const next=['Start with a warning or report. It opens a Watching case, not household claims.','Now inspect the sample observed-impact evidence. A weather warning alone cannot open a response.','Check the source, observation time, affected area and conflicting evidence. Then record the independent reviewer’s recommendation.','The reviewer has recommended this response. The primary approver or formally appointed backup can now authorize the same event terms.','The example response is approved. Household eligibility and payout confirmation are separate steps.'];
 const action=(name:string)=>o.technical?({'watch':'watch','evidence':'review','recommend':'approve-reviewer','authorize-primary':'approve-primary','authorize-backup':'approve-backup'}[name]||name):name;
 const control=(n:number,name:string,label:string,reason:string)=>`<button type="button" class="button ${stage===n-1?'primary':'secondary'}" data-action="${action(name)}" aria-describedby="event-step-${n}-note" ${stage!==n-1||o.locked||o.blocked?'disabled':''}>${label}</button><p id="event-step-${n}-note" class="event-action-note">${o.locked?'Locked while a household request uses these event terms.':o.blocked?escape(o.blocked):stage>=n?'Completed in this example.':stage===n-1?'Available now.':reason}</p>`;
 return `<section class="event-review" aria-labelledby="evidence-title"><div class="event-review-heading"><div><p class="eyebrow">EVENT AUTHORIZATION · SIMULATED ROLES</p><h2 id="evidence-title">Disaster evidence review</h2><p>First decide whether to open a relief response. Review individual household requests separately after the response is approved.</p></div><span class="event-stage-badge">${labels[stage]}</span></div>
 <div class="event-explainer"><div class="event-next"><span class="eyebrow">${stage===4?'RESPONSE STATUS':'YOUR NEXT STEP'}</span><h3 tabindex="-1" aria-describedby="event-next-detail">${labels[stage]}</h3><p id="event-next-detail">${o.locked?'This event is already attached to a household request. Its area, grant and approvals are locked so the request cannot change underneath the reviewer. Continue the household review below.':next[stage]}</p>${o.blocked?`<p class="event-blocked">${escape(o.blocked)}</p>`:''}<dl><div><dt>Evidence reviewer</dt><dd>${o.recommended?'Recommendation recorded':'Waiting for evidence review'}</dd></div><div><dt>Event approver</dt><dd>${o.approver==='primary'?'Primary approval recorded':o.approver==='backup'?'Backup approval recorded':'Waiting for recommendation'}</dd></div></dl></div>
 <details class="event-evidence" ${stage===1||stage===2?'open':''}><summary>Read the sample evidence and verification checks</summary><p><strong>Fictional observation:</strong> homes inundated and access to essentials disrupted. This is a scripted example, not a live news report.</p><dl><div><dt>Example area</dt><dd>${escape(o.area)}</dd></div><div><dt>Evidence source</dt><dd>Demo fixture · no official notice or live feed attached</dd></div></dl><h3>What a real reviewer would check</h3><ul><li>Original official notice or independently corroborated observations.</li><li>When the impact was observed, where it occurred and whether the source supports that exact area.</li><li>Conflicting reports, reused images and several articles repeating the same source.</li></ul><p>AI could collect and compare evidence in the planned service. It does not verify this example or authorize funds. Uncertain evidence needs human review.</p></details></div>
 <ol class="event-steps"><li class="${stage>=1?'is-complete':''}"><span class="event-step-number">01</span><h3>Watch for risk</h3><p>A warning or resident tip starts monitoring. No claims open and no money is sent.</p>${control(1,'watch','Start Watching','Start here to explore the sequence.')}</li><li class="${stage>=2?'is-complete':''}"><span class="event-step-number">02</span><h3>Review observed impact</h3><p>Inspect the fictional flood evidence. Observed impact is different from a forecast.</p>${control(2,'evidence','Open sample evidence','Complete step 01 first.')}</li><li class="${stage>=3?'is-complete':''}"><span class="event-step-number">03</span><h3>Record a recommendation</h3><p>The independent reviewer recommends the affected area and response terms.</p>${control(3,'recommend','Record reviewer recommendation','Open the evidence in step 02 first.')}</li><li class="${stage>=4?'is-complete':''}"><span class="event-step-number">04</span><h3>Authorize the response</h3><p>Choose the primary approver, or the formally appointed backup if the primary is unavailable. Both are not required.</p>${control(4,'authorize-primary','Approve as primary','Record the reviewer recommendation in step 03 first.')}<button type="button" class="button secondary" data-action="${action('authorize-backup')}" aria-describedby="event-step-4-note" ${stage!==3||o.locked||o.blocked?'disabled':''}>Use authorized backup</button></li></ol>
 <div class="event-review-foot"><p>These buttons simulate separate roles. They do not sign a reserve-program transaction or send a grant. Approval opens the next stage; it is not a payment receipt.</p>${!o.technical?o.locked?'<a href="#tracking">Continue household request →</a>':stage===4?'<a href="#receiver">Explore the household journey →</a>':'<a href="#home">Back to the scenario map →</a>':''}</div>
 ${!o.technical&&stage>0&&!o.locked?'<button type="button" class="link-button" data-action="restart-evidence">Restart event example (clears these sample approvals)</button>':''}
 </section>`;
}
