import logo from './assets/brand/reliefvue-elephant-selected.png';
import type {Locale} from './i18n';
import './mobile-app-preview.css';

export function mobileAppPreview(locale:Locale){
 const t=(en:string,th:string)=>locale==='th'?th:en;
 const device=(role:string,content:string)=>`<div class="app-device app-device-${role}"><div class="app-device-screen"><div class="app-device-status" aria-hidden="true">9:41 <i></i> ▰</div><div class="app-device-brand"><img src="${logo}" alt=""><strong>ReliefVue</strong><span>EN / ไทย</span></div>${content}<div class="app-device-nav" aria-hidden="true">⌂ &nbsp; ${t('Home','หน้าหลัก')} &nbsp; ◇ &nbsp; ${t('Activity','รายการ')} &nbsp; ☺</div><div class="app-device-home" aria-hidden="true"></div></div></div>`;
 const kyc=`<p class="app-screen-label">${t('YOUR HOUSEHOLD','ครัวเรือนของคุณ')}</p><h3>${t('Ready before an emergency.','เตรียมพร้อมก่อนเหตุฉุกเฉิน')}</h3><div class="app-identity"><span>✓</span><strong>${t('Verification complete','ยืนยันข้อมูลแล้ว')}</strong><small>${t('Sample household · Mae Rim','ครัวเรือนตัวอย่าง · แม่ริม')}</small></div><div class="app-check"><b>✓</b><div>${t('Identity','ตัวตน')}<small>${t('Government ID verified','ยืนยันเอกสารประจำตัวแล้ว')}</small></div></div><div class="app-check"><b>✓</b><div>${t('Home address','ที่อยู่')}<small>${t('Residence proof reviewed','ตรวจสอบหลักฐานที่อยู่แล้ว')}</small></div></div><div class="app-check"><b>✓</b><div>${t('Household details','ข้อมูลครัวเรือน')}<small>${t('One household · one grant','หนึ่งครัวเรือน · หนึ่งสิทธิ์')}</small></div></div><div class="app-private">♧ ${t('Documents stay private and off-chain.','เอกสารเป็นส่วนตัวและอยู่นอกบล็อกเชน')}</div><div class="app-preview-action">${t('View household','ดูข้อมูลครัวเรือน')} →</div>`;
 const overview=`<p class="app-screen-label">${t('THAILAND · SAMPLE RESPONSE','ประเทศไทย · ตัวอย่างการช่วยเหลือ')}</p><h3>${t('Relief at a glance.','ภาพรวมความช่วยเหลือ')}</h3><div class="app-total"><small>${t('Total received','ยอดรับทั้งหมด')}</small><strong>55,920 <em>SOL</em></strong><span>↗ ${t('Into the relief reserve','เข้าสู่กองทุนช่วยเหลือ')}</span></div><div class="app-overview-grid"><div><small>${t('Grants sent','ส่งเงินช่วยเหลือแล้ว')}</small><strong>7,680</strong><span>SOL</span></div><div><small>${t('Reserve balance','ยอดคงเหลือ')}</small><strong>48,240</strong><span>SOL</span></div></div><div class="app-impact"><strong>9,600</strong><span>${t('households supported','ครัวเรือนได้รับความช่วยเหลือ')}</span><div class="app-impact-bar"><i></i></div><small>${t('0.8 SOL per household · demo','0.8 SOL ต่อครัวเรือน · สาธิต')}</small></div><div class="app-transfer"><span>↗</span><div>${t('Household grant sent','ส่งเงินช่วยเหลือครัวเรือน')}<small>Mae Rim · 7L8c…G4p2</small></div><b>0.8 SOL</b></div>`;
 const alerts=`<p class="app-screen-label">${t('AREA ALERTS','การแจ้งเตือนในพื้นที่')}</p><h3>${t('Know your area.','ติดตามพื้นที่ของคุณ')}</h3><div class="app-alert"><b>! ${t('Flood response active','เปิดการช่วยเหลือน้ำท่วม')}</b><small>Mae Rim · ${t('Today, 11:06','วันนี้ 11:06')}</small></div><div class="app-map" role="img" aria-label="${t('Illustrative Mae Rim alert map, not a geographical flood boundary','แผนที่แจ้งเตือนแม่ริมแบบภาพประกอบ ไม่ใช่ขอบเขตน้ำท่วมจริง')}"><svg viewBox="0 0 240 200" aria-hidden="true"><path d="M0 38L240 80M-10 160L240 125M55 0L115 200M190 0L140 200" stroke="#fdfbf7" stroke-width="13"/><path d="M95 -10Q160 50 100 95T130 220" stroke="#b4cfd6" stroke-width="19" fill="none"/><ellipse cx="135" cy="104" rx="53" ry="42" fill="#ed997e55" stroke="#d97960" stroke-dasharray="5 4"/><circle cx="138" cy="99" r="9" fill="#6840b5"/><circle cx="138" cy="99" r="3" fill="white"/></svg><span>Mae Rim</span><small>${t('Illustrative map','แผนที่ภาพประกอบ')}</small></div><div class="app-area-detail"><strong>${t('Your verified home','บ้านที่ยืนยันแล้ว')}</strong><span>Mae Rim, Chiang Mai</span><small>${t('Affected area · request available','พื้นที่ได้รับผลกระทบ · ขอความช่วยเหลือได้')}</small></div><div class="app-preview-action">${t('Request household grant','ขอเงินช่วยเหลือครัวเรือน')} →</div>`;
 return `<section class="mobile-app-section" aria-labelledby="mobile-app-heading"><div class="container mobile-app-layout"><div class="mobile-app-copy"><p class="eyebrow">${t('THE RELIEFVUE MOBILE APP','แอปมือถือ RELIEFVUE')}</p><h2 id="mobile-app-heading">${t('Your household. Your relief. One app.','ครัวเรือนของคุณ ความช่วยเหลือของคุณ ในแอปเดียว')}</h2><p>${t('Prepare your household, follow local alerts and see how relief reaches people.','เตรียมข้อมูลครัวเรือน ติดตามการแจ้งเตือนในพื้นที่ และดูเส้นทางเงินช่วยเหลือ')}</p><div class="mobile-app-platforms"><span>iOS · ${t('Coming soon','เร็ว ๆ นี้')}</span><span>Android · ${t('Coming soon','เร็ว ๆ นี้')}</span></div><p class="mobile-app-availability">${t('App preview · fictional data · Thailand first · English / ไทย','ตัวอย่างแอป · ข้อมูลสมมติ · เริ่มที่ไทย · English / ไทย')}</p><a class="mobile-app-demo-link" href="#receiver">${t('Try the household web demo','ทดลองใช้งานสาธิตสำหรับครัวเรือนบนเว็บ')} ↗</a></div><figure class="mobile-app-figure"><div class="app-device-group">${device('left',kyc)}${device('center',overview)}${device('right',alerts)}</div><figcaption>${t('Household verification · Fund overview · Disaster alerts','การยืนยันครัวเรือน · ภาพรวมกองทุน · การแจ้งเตือนภัย')}</figcaption></figure></div></section>`;
}
