import logo from './assets/brand/reliefvue-elephant-selected.png';
import type {Locale} from './i18n';
import './mobile-app-preview.css';

/** A product preview, not a downloadable app or functioning sign-in form. */
export function mobileAppPreview(locale:Locale){
 const th=locale==='th';
 const t=(en:string,thai:string)=>th?thai:en;
 return `<section class="mobile-app-section" aria-labelledby="mobile-app-heading"><div class="container mobile-app-layout">
 <div class="mobile-app-copy"><p class="eyebrow">${t('THE RELIEFVUE MOBILE APP','แอปมือถือ RELIEFVUE')}</p><h2 id="mobile-app-heading">${t('ReliefVue, on your phone.','ReliefVue บนมือถือของคุณ')}</h2><p class="mobile-app-lead">${t('Keep your household details and relief requests in one place.','จัดการข้อมูลครัวเรือนและคำขอความช่วยเหลือในที่เดียว')}</p><p>${t('The planned app is where households will verify their details, request a grant for an activated affected area, and follow its progress. Donors can continue to give through the website.','แอปที่วางแผนไว้จะให้ครัวเรือนยืนยันข้อมูล ขอเงินช่วยเหลือเมื่อเปิดการช่วยเหลือในพื้นที่ที่ได้รับผลกระทบ และติดตามสถานะ ผู้บริจาคยังสามารถบริจาคผ่านเว็บไซต์ได้')}</p>
 <ol class="mobile-app-steps"><li><span aria-hidden="true">01</span>${t('Create your household account','สร้างบัญชีครัวเรือน')}</li><li><span aria-hidden="true">02</span>${t('Verify your identity and home privately','ยืนยันตัวตนและที่อยู่เป็นการส่วนตัว')}</li><li><span aria-hidden="true">03</span>${t('Request support when your area is activated','ขอความช่วยเหลือเมื่อเปิดการช่วยเหลือในพื้นที่ของคุณ')}</li></ol>
 <div class="mobile-app-platforms" aria-label="${t('Planned mobile availability','แพลตฟอร์มมือถือที่วางแผนไว้')}"><div><strong>iOS</strong><span>${t('Coming soon','เร็ว ๆ นี้')}</span></div><div><strong>Android</strong><span>${t('Coming soon','เร็ว ๆ นี้')}</span></div></div>
 <p class="mobile-app-availability">${t('App preview only. No download is available yet. Thailand first · English and Thai.','ภาพตัวอย่างแอปเท่านั้น ยังไม่มีแอปให้ดาวน์โหลด เริ่มที่ประเทศไทย · ภาษาอังกฤษและไทย')}</p><a class="mobile-app-demo-link" href="#receiver">${t('Try the household web demo','ทดลองใช้งานสาธิตสำหรับครัวเรือนบนเว็บ')} <span aria-hidden="true">↗</span></a></div>
 <figure class="mobile-app-figure"><div class="mobile-app-phone"><div class="mobile-app-screen"><div class="mobile-app-device-bar" aria-hidden="true"><span>9:41</span><i></i><span>● ▰</span></div><div class="mobile-app-preview-label">${t('APP PREVIEW','ตัวอย่างแอป')}</div><div class="mobile-app-phone-brand"><img src="${logo}" alt=""><span>ReliefVue</span></div><div class="mobile-app-phone-languages" aria-hidden="true"><span class="${th?'':'selected'}">EN</span><span class="${th?'selected':''}">ไทย</span></div><h3>${t('Welcome to ReliefVue','ยินดีต้อนรับสู่ ReliefVue')}</h3><p>${t('Prepare your household before an emergency.','เตรียมข้อมูลครัวเรือนก่อนเกิดเหตุฉุกเฉิน')}</p><div class="mobile-app-login-preview"><span>${t('Email or mobile number','อีเมลหรือหมายเลขโทรศัพท์')}</span><div>${t('Enter your details','กรอกข้อมูลของคุณ')}</div><span>${t('Password','รหัสผ่าน')}</span><div class="mobile-app-password" aria-hidden="true">••••••••</div><span class="mobile-app-forgot">${t('Forgot password?','ลืมรหัสผ่าน?')}</span><div class="mobile-app-signin">${t('Sign in','เข้าสู่ระบบ')}</div><div class="mobile-app-create">${t('Create an account','สร้างบัญชี')}</div></div><div class="mobile-app-phone-privacy"><svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M6 10h12v10H6zM8 10V7a4 4 0 0 1 8 0v3" stroke="currentColor" stroke-width="1.7" stroke-linejoin="round"/></svg><span>${t('Your identity and documents stay private.','ตัวตนและเอกสารของคุณเป็นข้อมูลส่วนตัว')}</span></div><div class="mobile-app-home-indicator" aria-hidden="true"></div></div></div><figcaption>${t('Proposed sign-in screen · not a live mobile app','หน้าจอเข้าสู่ระบบที่เสนอ · ยังไม่ใช่แอปที่เปิดใช้งานจริง')}</figcaption></figure>
 </div></section>`;
}
