import L from 'leaflet';
import 'leaflet/dist/leaflet.css';
import {scenarioReports, scenarioProvinces, type ScenarioReport} from './scenario-reports';
import {localize, type Locale} from './i18n';
const escape = (s:string) => s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export function scenarioMapMarkup(){return `<section class="scenario-section" aria-labelledby="scenario-heading">
 <div class="section-heading"><div><p class="eyebrow">ON THE GROUND · THAILAND</p><h2 id="scenario-heading">See the need.<br>Understand the response.</h2></div><p>Choose a province to explore simulated incident reports and review outcomes. A community report starts a review; it does not automatically release a grant.</p></div>
 <div class="scenario-toolbar"><span class="scenario-disclaimer">INCIDENT SIMULATION · NOT LIVE</span><div><button type="button" class="button secondary" data-report-open>Report an incident</button></div></div>
 <div class="province-filter"><label for="report-province">Province</label><select id="report-province">${scenarioProvinces.map(p=>`<option value="${p}">${p}</option>`).join('')}</select><span>Five province scenarios · fictional reports</span></div><div class="scenario-layout"><aside class="report-sidebar" aria-label="Incident records"><label for="report-search">Find a place or incident</label><input id="report-search" type="search" placeholder="Try Saraphi or flooding" autocomplete="off"><p class="report-result-count" role="status"></p><div class="report-list"></div></aside><div class="scenario-map-wrap"><div class="scenario-map" role="region" aria-label="Interactive Thailand incident simulation map"></div><button class="map-reset" type="button">Show all reports</button><div class="map-status-filters" role="group" aria-label="Filter map records"></div><p class="map-error" role="status" hidden>Map tiles are unavailable. The report list and location details still work.</p></div></div>
 <div class="map-legend"><span>Approximate area centres · simulated reports, not flood boundaries or live conditions.</span><span>Province selection changes the map only. Grant figures belong to the Chiang Mai response example.</span></div>
 <dialog class="incident-dialog" aria-labelledby="incident-title"><form class="incident-form"><div class="incident-dialog-head"><p class="eyebrow">COMMUNITY REPORT · DEMO</p><button type="button" data-report-close aria-label="Close report form">×</button></div><h2 id="incident-title">Report an incident</h2><p>Use fictional details only. This preview stays in your browser session and is not sent to AI, reviewers or emergency services.</p><label for="incident-kind">What happened?</label><select id="incident-kind" required><option>Flooding</option><option>Road impassable</option><option>Water supply disrupted</option><option>Household displacement</option><option>Other incident</option></select><label for="incident-location">Area or public landmark</label><input id="incident-location" required maxlength="100" placeholder="Example: a public road in Saraphi"><label for="incident-time">When was it observed?</label><input id="incident-time" type="datetime-local" required><label for="incident-detail">What did you observe?</label><textarea id="incident-detail" required minlength="15" maxlength="1000" rows="4" placeholder="Describe the conditions. Do not include names, household addresses or identity documents."></textarea><div class="report-review-path"><strong>Report → AI checks → Human review if uncertain</strong><p>AI would check relevance, consistency and possible duplicates. Uncertain reports need human verification before publication.</p></div><button class="button primary" type="submit">Preview report review</button><p class="incident-result" role="status" hidden></p></form></dialog>
 </section>`;}
export function initScenarioMap(root:HTMLElement, locale:Locale):()=>void {
 const section=root.querySelector<HTMLElement>('.scenario-section');if(!section)return ()=>{};
 const translate=(el:HTMLElement)=>localize(el,locale);
 const mapEl=section.querySelector<HTMLElement>('.scenario-map')!;
 const reduced=()=>matchMedia('(prefers-reduced-motion: reduce)').matches;
 const map=L.map(mapEl,{scrollWheelZoom:false,zoomAnimation:!reduced(),fadeAnimation:!reduced(),markerZoomAnimation:!reduced()});
 const tiles=L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'}).addTo(map);
 const error=section.querySelector<HTMLElement>('.map-error')!;
 tiles.on('tileerror',()=>{error.hidden=false;});
 const group=L.featureGroup().addTo(map);
 const markers=new Map<string,L.Marker>();
 const list=section.querySelector<HTMLElement>('.report-list')!;
 const input=section.querySelector<HTMLInputElement>('#report-search')!;
 const province=section.querySelector<HTMLSelectElement>('#report-province')!;
 let selected='',status='all';
 const records=()=>scenarioReports.filter(r=>r.province===province.value);
 const label=(r:ScenarioReport)=>r.status==='resolved'?'Resolved example':'Needs review';
 const popup=(r:ScenarioReport)=>{const node=document.createElement('div');node.className='report-popup';node.innerHTML=`<span>${r.source?'HISTORICAL RECORD':'FICTIONAL REPORT'} · ${escape(r.id)}</span><h3>${escape(r.incident)}</h3><strong>${escape(r.name)}</strong><p>${escape(r.address)}</p><p>${escape(r.detail)}</p><small>${escape(r.time)} · ${r.coordinates.join(', ')}<br><span>Approximate area centre</span></small>${r.source?`<p><a target="_blank" rel="noopener" href="${escape(r.source.url)}">Source: ${escape(r.source.label)} ↗</a></p>`:''}${r.image?`<figure><img src="${escape(r.image.src)}" alt="${escape(r.image.alt)}"><figcaption>${escape(r.image.caption)}</figcaption></figure>`:'<p class="report-photo-note">No verified photo supplied.</p>'}`;translate(node);return node;};
 const select=(r:ScenarioReport,pan=true)=>{selected=r.id;list.querySelectorAll<HTMLButtonElement>('[data-report]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.report===selected)));if(pan)map.setView(r.coordinates,13,{animate:!reduced()});markers.get(r.id)?.openPopup();};
 scenarioReports.forEach(r=>{const marker=L.marker(r.coordinates,{title:`${r.name}: ${r.incident} (${r.source?'2024 historical record':'fictional'})`,icon:L.divIcon({className:`scenario-pin ${r.status==='resolved'?'resolved':''}`,html:`<svg viewBox="0 0 40 48" aria-hidden="true"><path d="M20 46S3 28 3 19a17 17 0 1 1 34 0c0 9-17 27-17 27Z"/><text x="20" y="25" text-anchor="middle">${r.status==='resolved'?'✓':'!'}</text></svg>`,iconSize:[44,52],iconAnchor:[22,50]})}).bindPopup(popup(r),{maxWidth:280});marker.on('click',()=>select(r,false));markers.set(r.id,marker);});
 function filter(){const query=input.value.trim().toLocaleLowerCase();const reports=records().filter(r=>(status==='all'||label(r)===status)&&`${r.name} ${r.address} ${r.incident} ${r.detail} ${locale==='th'?thaiSearch[r.id]||'':''}`.toLocaleLowerCase().includes(query));map.stop();group.clearLayers();reports.forEach(r=>group.addLayer(markers.get(r.id)!));list.innerHTML=reports.length?reports.map(r=>`<button type="button" data-report="${r.id}" aria-pressed="${selected===r.id}"><span class="report-meta"><span>${r.time}</span><span>${label(r)}</span></span><strong><i class="report-dot ${r.status==='resolved'?'resolved':''}" aria-hidden="true"></i>${escape(r.incident)}</strong><span class="report-place">${escape(r.name)} <span aria-hidden="true">↗</span></span><small>${escape(r.address)}</small></button>`).join(''):'<p class="report-empty">No example reports match. Try another place or incident.</p>';const count=section!.querySelector<HTMLElement>('.report-result-count')!;count.textContent=locale==='th'?`${reports.length} รายงานสมมติ`:`${reports.length} simulated reports · ${province.value}`;translate(list);list.querySelectorAll<HTMLButtonElement>('[data-report]').forEach(b=>b.onclick=()=>select(records().find(r=>r.id===b.dataset.report)!));if(reports.length)map.fitBounds(group.getBounds(),{paddingTopLeft:[45,60],paddingBottomRight:[45,100],maxZoom:13,animate:false});}
 input.oninput=filter;filter();
 section.querySelector<HTMLButtonElement>('.map-reset')!.onclick=()=>{input.value='';selected='';status='all';map.closePopup();drawControls();filter();};
 const controls=section.querySelector<HTMLElement>('.map-status-filters')!;
 const drawControls=()=>{const options=['All','Needs review','Resolved example'];controls.innerHTML=options.map((name,i)=>`<button type="button" data-status="${i?name:'all'}" aria-pressed="${status===(i?name:'all')}"><span aria-hidden="true">${i===2?'✓':i===1?'!':'◉'}</span>${name}</button>`).join('');translate(controls);controls.querySelectorAll<HTMLButtonElement>('button').forEach(button=>button.onclick=()=>{status=button.dataset.status!;drawControls();filter();});};drawControls();
 province.onchange=()=>{status='all';input.value='';selected='';map.closePopup();drawControls();filter();};
 const dialog=section.querySelector<HTMLDialogElement>('dialog')!;const open=section.querySelector<HTMLButtonElement>('[data-report-open]')!;
 open.onclick=()=>dialog.showModal();section.querySelector<HTMLButtonElement>('[data-report-close]')!.onclick=()=>dialog.close();
 dialog.addEventListener('close',()=>open.focus());
 const form=section.querySelector<HTMLFormElement>('form')!;
 form.onsubmit=e=>{e.preventDefault();const result=section.querySelector<HTMLElement>('.incident-result')!;result.hidden=false;result.textContent='Preview only: awaiting human verification. This demo cannot validate evidence, so the report remains unpublished. In the planned service, AI would assess it first and escalate uncertain cases to a human. Nothing has been submitted or added to the map.';translate(result);result.scrollIntoView({block:'nearest',behavior:reduced()?'instant':'smooth'});};
 const resize=new ResizeObserver(()=>map.invalidateSize({pan:false}));resize.observe(mapEl);
 return ()=>{resize.disconnect();map.remove();};
}
const thaiSearch:Record<string,string>={'CM-106':'ช้างเผือก น้ำท่วม','CM-105':'สารภี ถนนสัญจรไม่ได้','CM-104':'เมืองเก่า น้ำประปา','CM-103':'แม่ริม น้ำท่วม','CM-102':'หางดง เปิดเส้นทาง','CM-101':'สันทราย สิ่งของ'};
