import L from 'leaflet';
import 'leaflet/dist/leaflet.css';
import {scenarioReports, type ScenarioReport} from './scenario-reports';
import {localize, type Locale} from './i18n';
const escape = (s:string) => s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export function scenarioMapMarkup(){return `<section class="scenario-section" aria-labelledby="scenario-heading">
 <div class="section-heading"><div><p class="eyebrow">ON THE GROUND · FICTIONAL REPORTS</p><h2 id="scenario-heading">See the need.<br>Understand the response.</h2></div><p>Explore example reports across Chiang Mai. A report starts a review; it does not confirm a disaster or automatically release a grant.</p></div>
 <div class="scenario-toolbar"><span class="scenario-disclaimer">SCENARIO MAP · NOT LIVE</span><div><button type="button" class="map-motion" aria-pressed="false">Pause map pulses</button><button type="button" class="button secondary" data-report-open>Report an incident</button></div></div>
 <div class="scenario-layout"><aside class="report-sidebar" aria-label="Example incident reports"><label for="report-search">Find a place or incident</label><input id="report-search" type="search" placeholder="Try Saraphi or flooding" autocomplete="off"><p class="report-result-count" role="status"></p><div class="report-list"></div></aside><div class="scenario-map-wrap"><div class="scenario-map" role="region" aria-label="Interactive fictional Chiang Mai incident map"></div><button class="map-reset" type="button">Show all reports</button><p class="map-error" role="status" hidden>Map tiles are unavailable. The report list and location details still work.</p></div></div>
 <div class="map-legend"><span><i class="report-dot" aria-hidden="true"></i>Needs review</span><span><i class="report-dot resolved" aria-hidden="true"></i>Resolved example</span><span>Approximate area centres · no household locations</span></div>
 <dialog class="incident-dialog" aria-labelledby="incident-title"><form class="incident-form"><div class="incident-dialog-head"><p class="eyebrow">COMMUNITY REPORT · DEMO</p><button type="button" data-report-close aria-label="Close report form">×</button></div><h2 id="incident-title">Report an incident</h2><p>Use fictional details only. This preview stays in your browser session and is not sent to AI, reviewers or emergency services.</p><label for="incident-kind">What happened?</label><select id="incident-kind" required><option>Flooding</option><option>Road impassable</option><option>Water supply disrupted</option><option>Supplies needed</option><option>Other incident</option></select><label for="incident-location">Area or public landmark</label><input id="incident-location" required maxlength="100" placeholder="Example: a public road in Saraphi"><label for="incident-time">When was it observed?</label><input id="incident-time" type="datetime-local" required><label for="incident-detail">What did you observe?</label><textarea id="incident-detail" required minlength="15" maxlength="1000" rows="4" placeholder="Describe the conditions. Do not include names, household addresses or identity documents."></textarea><div class="report-review-path"><strong>Report → AI checks → Human review if uncertain</strong><p>AI would check relevance, consistency and possible duplicates. Uncertain reports need human verification before publication.</p></div><button class="button primary" type="submit">Preview report review</button><p class="incident-result" role="status" hidden></p></form></dialog>
 </section>`;}
export function initScenarioMap(root:HTMLElement, locale:Locale):()=>void {
 const section=root.querySelector<HTMLElement>('.scenario-section');if(!section)return ()=>{};
 const translate=(el:HTMLElement)=>localize(el,locale);
 const mapEl=section.querySelector<HTMLElement>('.scenario-map')!;
 const reduced=()=>matchMedia('(prefers-reduced-motion: reduce)').matches;
 const map=L.map(mapEl,{scrollWheelZoom:false,zoomAnimation:!reduced(),fadeAnimation:!reduced(),markerZoomAnimation:!reduced()});
 const tiles=L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'}).addTo(map);
 const error=section.querySelector<HTMLElement>('.map-error')!;
 tiles.on('tileerror',()=>{error.hidden=false;});
 const group=L.featureGroup().addTo(map);
 const markers=new Map<string,L.Marker>();
 const list=section.querySelector<HTMLElement>('.report-list')!;
 const input=section.querySelector<HTMLInputElement>('#report-search')!;
 let selected='';
 const popup=(r:ScenarioReport)=>{const node=document.createElement('div');node.className='report-popup';node.innerHTML=`<span>FICTIONAL REPORT · ${escape(r.id)}</span><h3>${escape(r.incident)}</h3><strong>${escape(r.name)}</strong><p>${escape(r.address)}</p><p>${escape(r.detail)}</p><small>${escape(r.time)} · ${r.coordinates.join(', ')}<br><span>Approximate area centre</span></small>${r.image?`<figure><img src="${escape(r.image.src)}" alt="${escape(r.image.alt)}"><figcaption>${escape(r.image.caption)}</figcaption></figure>`:'<p class="report-photo-note">No verified photo supplied.</p>'}`;translate(node);return node;};
 const select=(r:ScenarioReport,pan=true)=>{selected=r.id;list.querySelectorAll<HTMLButtonElement>('[data-report]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.report===selected)));if(pan)map.setView(r.coordinates,13,{animate:!reduced()});markers.get(r.id)?.openPopup();};
 scenarioReports.forEach(r=>{const marker=L.marker(r.coordinates,{title:`${r.name}: ${r.incident} (fictional)`,icon:L.divIcon({className:`scenario-pin ${r.status==='resolved'?'resolved':''}`,html:'<span></span>',iconSize:[44,44],iconAnchor:[22,22]})}).bindPopup(popup(r),{maxWidth:280});marker.on('click',()=>select(r,false));markers.set(r.id,marker);});
 function filter(){const query=input.value.trim().toLocaleLowerCase();const reports=scenarioReports.filter(r=>`${r.name} ${r.address} ${r.incident} ${r.detail} ${locale==='th'?thaiSearch[r.id]||'':''}`.toLocaleLowerCase().includes(query));group.clearLayers();reports.forEach(r=>group.addLayer(markers.get(r.id)!));list.innerHTML=reports.length?reports.map(r=>`<button type="button" data-report="${r.id}" aria-pressed="${selected===r.id}"><span class="report-meta"><span>${r.time}</span><span>${r.status==='resolved'?'Resolved example':'Needs review'}</span></span><strong><i class="report-dot ${r.status==='resolved'?'resolved':''}" aria-hidden="true"></i>${escape(r.incident)}</strong><span class="report-place">${escape(r.name)} <span aria-hidden="true">↗</span></span><small>${escape(r.address)}</small></button>`).join(''):'<p class="report-empty">No example reports match. Try another place or incident.</p>';const count=section!.querySelector<HTMLElement>('.report-result-count')!;count.textContent=locale==='th'?`รายงานสมมติ ${reports.length} รายการ`:`${reports.length} fictional reports`;translate(list);list.querySelectorAll<HTMLButtonElement>('[data-report]').forEach(b=>b.onclick=()=>select(scenarioReports.find(r=>r.id===b.dataset.report)!));if(reports.length)map.fitBounds(group.getBounds(),{padding:[40,40],maxZoom:13,animate:false});}
 input.oninput=filter;filter();
 section.querySelector<HTMLButtonElement>('.map-reset')!.onclick=()=>{input.value='';selected='';map.closePopup();filter();};
 section.querySelector<HTMLButtonElement>('.map-motion')!.onclick=e=>{const button=e.currentTarget as HTMLButtonElement;const paused=section.classList.toggle('pulses-paused');button.setAttribute('aria-pressed',String(paused));button.textContent=paused?'Resume map pulses':'Pause map pulses';translate(button);};
 const dialog=section.querySelector<HTMLDialogElement>('dialog')!;const open=section.querySelector<HTMLButtonElement>('[data-report-open]')!;
 open.onclick=()=>dialog.showModal();section.querySelector<HTMLButtonElement>('[data-report-close]')!.onclick=()=>dialog.close();
 dialog.addEventListener('close',()=>open.focus());
 const form=section.querySelector<HTMLFormElement>('form')!;
 form.onsubmit=e=>{e.preventDefault();const result=section.querySelector<HTMLElement>('.incident-result')!;result.hidden=false;result.textContent='Preview only: awaiting human verification. This demo cannot validate evidence, so the report remains unpublished. In the planned service, AI would assess it first and escalate uncertain cases to a human. Nothing has been submitted or added to the map.';translate(result);result.scrollIntoView({block:'nearest',behavior:reduced()?'instant':'smooth'});};
 const resize=new ResizeObserver(()=>map.invalidateSize({pan:false}));resize.observe(mapEl);
 return ()=>{resize.disconnect();map.remove();};
}
const thaiSearch:Record<string,string>={'CM-106':'ช้างเผือก น้ำท่วม','CM-105':'สารภี ถนนสัญจรไม่ได้','CM-104':'เมืองเก่า น้ำประปา','CM-103':'แม่ริม น้ำท่วม','CM-102':'หางดง เปิดเส้นทาง','CM-101':'สันทราย สิ่งของ'};
